---
version: "2.1"
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /media/andy/EXT0/.plex/config:/config
      - /media/andy/NAS:/media-dad
      - /media/andy/EXT0/MEDIA:/media
    restart: unless-stopped

  deluge:
    image: ghcr.io/linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /media/andy/EXT0/.deluge/config:/config
      - /media/andy/EXT0/.deluge/downloads:/downloads
      - /media/andy/EXT0/.deluge/completed:/completed
    restart: unless-stopped

  # sonarr:
  #   image: ghcr.io/linuxserver/sonarr
  #   container_name: sonarr
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/London
  #     - UMASK_SET=022 #optional
  #   volumes:
  #     - /media/andy/EXT0/.sonarr/config:/config
  #     - /home/andy/.sonarr/tv:/tv
  #     - /home/andy/.deluge/downloads:/downloads
  #   ports:
  #     - 8989:8989
  #   restart: unless-stopped